### ISSUE TITLE
Retrieving verfication code failed

### ISSUE THREAD

**Issue by Shaun-Fong** [jcs090218/unity-verify-code#4]
<img width="616" alt="Capture" src="https://user-images.githubusercontent.com/16713354/170911663-38a9b971-6221-4752-92c9-0ff673fa16f2.PNG">

**Comment by Shaun-Fong** [comment]
I'm using gmail.
Secrets is setup already and IMAP service is enabled already.
Less secure apps is enabled too. 
But I still can not retrieving verfication code , any suggestions?

**Comment by jcs090218** [comment]
Can you try to retrieve the code manually from your local machine? Then we can better understand your issue, and further investigate it.

**Comment by Shaun-Fong** [comment]
> 

I think I know why now.
First time I run the code show me this
![1](https://user-images.githubusercontent.com/16713354/170916472-743aab25-a7b4-4408-962e-b51374935c55.png)
`Source Server Error:-  Error: Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)`

Check this [link](https://stackoverflow.com/questions/20337040/getting-error-while-sending-email-through-gmail-smtp-please-log-in-via-your-w)

Then I Visit this [link](http://www.google.com/accounts/DisplayUnlockCaptcha) to authorization. **This is the key I think**.
Run the code again I pass.

![2](https://user-images.githubusercontent.com/16713354/170916686-cecb88a1-2bc2-481a-a149-dac513c5c52b.png)

Problem solved.
![image](https://user-images.githubusercontent.com/16713354/170917332-fa139194-c19f-4c1e-be7c-2e9318b6b303.png)

BTW , you may want to check [this](https://support.google.com/accounts/answer/6010255)
`To help keep your account secure, starting May 30, 2022, ​​Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.`
Does this mean that this method can no longer be used?

**Comment by jcs090218** [comment]
I guess the issue is resolved? :)

> BTW , you may want to check [this](https://support.google.com/accounts/answer/6010255)
To help keep your account secure, starting May 30, 2022, ​​Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.
Does this mean that this method can no longer be used?

Yeah, this is unfortune. I am still thinking for other solution, but my suggestion for workaround is to use other services for now. 😓 

| Name    | Done | Value                   |
|---------|------|-------------------------|
| Gmail   | ✔    | `imap.gmail.com`        |
| Hotmail | ✔    | `imap-mail.outlook.com` |
| Outlook | ✔    | `imap-mail.outlook.com` |
| Yahoo   | ✔    | `imap.mail.yahoo.com`   |

(will add this to README later on, see #5)

**Comment by Shaun-Fong** [comment]
> 

What a pity , I just solved the problem lol
